markdown: redcarpet
safe: true
lsi: false
pygments: true
menu:
  - title: "Introduction"
    url: "/introduction.html"
  - title: "Binding data"
    url: "/binding_data.html"
  - title: "Models"
    url: "/models.html"
  - title: "Controllers"
    url: "/controllers.html"
  - title: "Templates"
    url: "/templates.html"
  - title: "Custom helpers"
    url: "/custom_helpers.html"
  - title: "Performance"
    url: "/performance.html"
  - title: "Development"
    url: "/development.html"
  - title: "HTML to Serenade converter"
    url: "/convert.html"
reference:
  - title: "Serenade.defineProperty"
    url: "/reference/define_property.html"
  - title: "Serenade.defineEvent"
    url: "/reference/define_event.html"
  - title: "Serenade.Model"
    url: "/reference/model.html"
  - title: "Serenade.Collection"
    url: "/reference/collection.html"
version:
  - 0.4.2
oldVersions:
  - 0.4.1
  - 0.4.0
  - 0.3.0
  - 0.2.1
  - 0.2.0
  - 0.1.3
  - 0.1.2
  - 0.1.1
  - 0.1.0
